
'use server';
/**
 * @fileOverview An AI flow to process text by explaining, summarizing, or expanding it.
 *
 * - processText - A function that handles text processing based on the specified action.
 * - ProcessTextInput - The input type for the processText function.
 * - ProcessTextOutput - The return type for the processText function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ProcessTextInputSchema = z.object({
  action: z.enum(['explain', 'summarize', 'expand']).describe('The AI action to perform on the text.'),
  text: z.string().min(1).describe('The text content to be processed.'),
  context: z.string().optional().describe('Optional context, like the current subject or topic of the notes.'),
});
export type ProcessTextInput = z.infer<typeof ProcessTextInputSchema>;

const ProcessTextOutputSchema = z.object({
  processedText: z.string().describe('The text generated by the AI based on the action.'),
});
export type ProcessTextOutput = z.infer<typeof ProcessTextOutputSchema>;

export async function processText(input: ProcessTextInput): Promise<ProcessTextOutput> {
  return processTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'processTextPrompt',
  input: { schema: ProcessTextInputSchema },
  output: { schema: ProcessTextOutputSchema },
  prompt: `You are an AI Study Assistant integrated into a note-taking application.
Your goal is to help users understand and work with their study notes.
The user is currently working on notes.
{{#if context}}
The broader context or subject of these notes is: "{{{context}}}"
{{/if}}

The user has selected the action: "{{action}}" for the following text.

Text to process:
"""
{{{text}}}
"""

Please perform the requested action:
{{#if (eq action "summarize")}}
- Action: Summarize the provided text.
- Goal: Condense the text to its core ideas and key takeaways. Aim for a significantly shorter version that captures the essence.
- Output Format: Provide only the summary text.
{{else if (eq action "explain")}}
- Action: Explain the provided text.
- Goal: Clarify the text, define key terms, break down complex concepts into simpler parts, or provide illustrative examples. Make it easier to understand.
- Output Format: Provide only the explanation text.
{{else if (eq action "expand")}}
- Action: Expand on the provided text.
- Goal: Elaborate on the text by adding more details, related concepts, examples, or further discussion points. Make the text more comprehensive.
- Output Format: Provide only the expanded text.
{{/if}}

Ensure your response DIRECTLY contains ONLY the processed text based on the action. Do not add any conversational preamble or sign-off.
`,
});

const processTextFlow = ai.defineFlow(
  {
    name: 'processTextFlow',
    inputSchema: ProcessTextInputSchema,
    outputSchema: ProcessTextOutputSchema,
  },
  async (input) => {
    if (!input.text || input.text.trim() === "") {
        return { processedText: "Cannot process empty text." };
    }
    const { output } = await prompt(input);
    if (!output) {
        throw new Error("AI failed to process the text.");
    }
    return output;
  }
);
